spring.application.name=trend-hunter-backend

spring.datasource.url=jdbc:h2:file:./data/tendancesdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true